### ISSUE TITLE
Set up SFTP server and integration profile for general publishing

### ISSUE THREAD

**Issue by kelynch** [pulibrary/alma_experimentation#10]
Set up an SFTP server that will allow for an Alma user to authenticate, then set up an Integration profile for general publishing.

See Alma documentation for more information - https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/050Administration/050Configuring_General_Alma_Functions/050External_Systems#Configuring_S.2FFTP_Connections

**Comment by kelynch** [comment]
SFTP server has been set up and tested locally.  IP ranges from Ex Libris have been greenlisted.  Connection test failed during testing last week, but we just had a successful connection test after adjusting credentials based on Ex Libris recommendation, and updating local firewall settings.

**Comment by mzelesky** [comment]
General publishing has been successfully run multiple times from the SFTP.

**Comment by hackartisan** [comment]
It would be helpful if this issue would point to the documentation of the location of the server, and/or the ansible PRs that created it.

**Comment by kelynch** [comment]
The FTP server was provisioned by the Ops team outside of ansible.  Location and connection info are on LastPass.
