### ISSUE TITLE
Review and Document Staff User Profiles

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/alma_experimentation#11]
List and compare our current voyager operator profiles to what is possible in Alma and note discrepancies/changes we need to make as we set up comparable profiles in the Alma Sandbox.

**Comment by pmgreen** [comment]
Documentation for Voyager profiles: https://files.mtstatic.com/site_11811/draft_54462/0?Expires=1594312113&Signature=WlDPdeDGYHXIl7No8acqt4opWk0skwfBzPMMu-gmBvsZ~VZZXhYz~AOQk5O-Eef-Mws8YzUNqu486Y5wQHkrxuMXnejsoqzzqJ4LwO5Mqiw2VZ-YZF3Gq4BuYTPAKL1I3GrgrYMCcPFAQhk40KOQekIIDJZBgyWYLtgXQobWG3M_&Key-Pair-Id=APKAJ5Y6AV4GI7A555NA
