### ISSUE TITLE
Set Up Shibboleth Authentication

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/alma_experimentation#21]
* Set up basic SAML Handshake with PUL Identity Provider
* For Staff
* For Patrons

**Comment by kevinreiss** [comment]
SAML Handshake Details

Basic SAML Handshake working set-up notes:
```
Look under ‘integration profiles’ in the sandbox
Alma SAML documentation
https://idp.princeton.edu/idp/shibboleth
This URL works as of 2020-06-24: https://sandbox02-na.alma.exlibrisgroup.com/institution/01PRI_INST/SAML/idpCode/SAML becomes https://sandbox02-na.alma.exlibrisgroup.com/mng/login?institute=01PRI_INST&auth=SAML (using default SAML profile)
SAML: https:///institution/{INST_CODE}/SAML/idpCode/{sandbox SAML integration profile code}
```

**Comment by pmgreen** [comment]
We need to give info to our IDP:
Audience = https://sandbox02-na.alma.exlibrisgroup.com/mng/login
Recipient = https://sandbox02-na.alma.exlibrisgroup.com/mng/pdsHandleLogin

The IDP must generate and send the ‘Relay state’ parameter:  mng@@01PRI_INST

**Comment by pmgreen** [comment]
Submitted a request via SN@P with @kevinreiss

**Comment by pmgreen** [comment]
Submitted more details to OIT on their request.

**Comment by pmgreen** [comment]
Posted OIT's questions in Basecamp for ExL (re: persistent IDs missing in metadata files)

**Comment by pmgreen** [comment]
ExL responded "There is no configuration in Alma to add or change the NameIDFormat value. ‘transient’ is the NameIDFormat Alma supports." This was not enough information. OIT has reached out to ExL directly and is waiting for a response.

**Comment by pmgreen** [comment]
https://sandbox02-na.alma.exlibrisgroup.com/mng/login?institute=01PRI_INST&auth=SAML
https://sandbox02-na.alma.exlibrisgroup.com/institution/01PRI_INST/SAML
