### ISSUE TITLE
move availability logic to bibdata

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/alma_experimentation#30]
Availability logic currently is in VoyagerHelpers. https://github.com/pulibrary/voyager_helpers/blob/37b62ad83ed2f1af6185e54534d901e23e5fdf30/lib/voyager_helpers/liberator.rb#L229

In Alma, PO lines for items can be returned in the Publishing jobs. Based on the location of a holding, Bibdata should retrieve the order status of an attached PO line. If it is an electronic resource, order status does not need to be retrieved. There are likely other criteria to look at as well.

**Comment by hackartisan** [comment]
Closing as a duplicate of pulibrary/marc_liberation#573
