### ISSUE TITLE
Configure a general publishing job via OAI to include necessary fields for full availability

### ISSUE THREAD

**Issue by kelynch** [pulibrary/alma_experimentation#9]
The feed needs to include holdings and item-level information.

**Comment by kelynch** [comment]
Builds on https://github.com/pulibrary/marc_liberation/issues/653

**Comment by christinach** [comment]
https://docs.google.com/spreadsheets/d/1xWA7lmICLp5sT2yROPyeKz_AbOsBa_nNhjNCDGDE2O8/edit#gid=0
